repos:
  - hooks:
    - id: commitizen
    - id: commitizen-branch
      stages:
      - push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0

  - repo: https://github.com/ambv/black
    rev: 24.1.1
    hooks:
    - id: black
      language_version: python3.10

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.14
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # # Run the formatter.
      # - id: ruff-format
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203,E712"]
