version: "3"
services:
  gammapy-tools:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      # Modify port as needed
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=letmein
    volumes:
      # Replace with where your data is located
      - /home/obriens/DataAnalysis/Veritas/Gammapy:/local_data  
      # - $GAMMAPY_DATA:/gammapy-tools/gammapy-datasets/1.1/