io:
    search_datastore : "/gamma_data/MegaStore/moderate2tel_runwise_backgrounds_nosmooth/"
    in_dir : "/gamma_data/Crab_data/"
    out_dir : "/gamma_data/Crab_data_runwise_backgrounds_nosmooth/"
    results_dir : "/gamma_data/Crab_data_runwise_backgrounds_nosmooth/results/"
    # Whether or not to generate the background from the run
    from_run : False  

binning:
    # Energy binning
    e_min: 0.1
    e_max: 100
    e_bins: 20
    # Offset/wobble binning
    off_min: 0
    off_max: 2.5
    off_bins: 5

config:
    njobs : 10

exclusion:
    star_cat : "./Hipparcos_MAG8_1997.dat"
    # Exculde region around a simbad resolveable source name
    # Expecting name, exclusion
    exclude_source_name : [ ("MGRO J1908+06", "0.5 deg"]
    # Exculde region around a given ra, dec
    exclude_regions :
        - ["276.56273398", "-14.84840202", "0.5"]
    # Exculde region around a given ra, dec
    # Exculde region around a given ra, dec
    # exclude_source_pos : [ ("287.10 deg", "6.39 deg", "0.5 deg"]
    # Exculde entire run within a distance to a given ra/dec
    # Expecting ra, dec, exclusion
    # exclude_source_run : [ ("287.10 deg", "6.39 deg", "3.5 deg"]


background_selection:
    # el_min : 40
    # el_max : 30
    nsb_diff : 0.7
    # 1/sin(el) difference
    el_diff : 0.15
    # az difference
    az_diff : 45
    # Minimum number of telescopes
    n_tels : 4
    # Maximum time between runs in days
    time_max : 180
    # Whether or not to smooth the background
    smooth : False


analysis_selection:
    theta2 : 0.008

run_selection:
    # Runs of interests
    runlist : [ 69054, 69123, 69187, 69188, 69202, 69203, 73193, 73213, 73234, 73300, 73317, 73335, 73356, 73357, 73390, 73403, 73607]    
    # Source of interest
    source_name : "LS5039"
    source_ra : 276.56273398
    source_dec : -14.84840202
    # Coords to search around
    # coords : ["287.10 deg", "6.39 deg"]
    # coords_galactic : ["40.39 deg", "-0.79 deg"]
    # Maximum offset to select data from
    offset_max : 1.5
    # Number of telescopes to select
    n_tel : 4
    # elevation min/maz
    el_min : 40
    # el_max : 90
    # Time range (d/m/y)
    # time_min : "01/09/2007"
    # time_max : "01/09/2025"